language: rust
matrix:
  include:
    - rust: stable
    - rust: stable
      env: FEATURES='-no-default-features --features sdl_backend'
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev libegl1-mesa-dev libgles2-mesa-dev
